Add option to flip the board display
dwcoates/pygn-mode pull request #151
Opened 2021-07-09 21:47 UTC by qnix

M-x pygn-mode-flip-board

2021-07-10 22:09 UTC, dwcoates requested changes

2021-07-14 01:32 UTC, qnix commented on pygn-mode.el
> +  (setq pygn-mode-board-flipped (not pygn-mode-board-flipped)))
Yes!  Thank you for  the code  change.

2021-07-14 13:04 UTC, dwcoates approved these changes

2021-07-14 13:04 UTC, merged

2021-07-14 13:04 UTC, dwcoates commented
Thanks! Merged!